import { useApp } from '../context/AppContext';

export function useWallet() {
  const {
    auth,
    wallet,
    login,
    register,
    logout,
    connectWallet,
    disconnectWallet,
    walletConnected,
    walletAddress,
    shortWalletAddress,
    selectedRole,
    setSelectedRole,
    isAuthenticated,
    userRole,
    currentUser,
    hasFreighter,
    poolState,
    users,
    transactionHistory,
    payoutHistory,
    userProfile,
    myActivity,
    loading,
    loadingAction,
    errorMessage,
    successMessage,
    contribute,
    triggerStorm,
  } = useApp();

  return {
    auth,
    currentUser,
    isAuthenticated,
    userRole,
    walletConnected,
    walletAddress,
    shortWalletAddress,
    walletState: wallet,
    selectedRole,
    setSelectedRole,
    hasFreighter,
    poolState,
    users,
    transactionHistory,
    payoutHistory,
    userProfile,
    myActivity,
    loading,
    loadingAction,
    errorMessage,
    successMessage,
    contribute,
    triggerStorm,
    connectWallet,
    disconnectWallet,
    login,
    register,
    logout,
  };
}